/**
 * 
 */
package net.suteren.vcard;

public enum Relations {
	HOME, OTHER, WORK, FAX, HOME_FAX, MOBILE, PAGER, WORK_FAX, NETMEETING, ASSISTANT, CALLBACK, CAR, COPMANY_MAIN, ISDN, MAIN, OTHER_FAX, RADIO, TELEX, TTY_TDD, WORK_MOBILE, WORK_PAGER,

	OVERALL, PRICE, QUALITY,

	EVENT, EVENT_ALTERNATE, EVENT_PARKING, EVENT_ATTENDEE, EVENT_ORGANIZER, EVENT_PERFORMER, EVENT_SPEAKER,

	MESSAGE_BCC, MESSAGE_CC, MESSAGE_FROM, MESSAGE_REPLY_TO, MESSAGE_TO,

	REGULAR, REVIEWS;

}